### ISSUE TITLE
case.setup fails on edison

### ISSUE THREAD

**Issue by mark-petersen** [E3SM-Project/E3SM#2374]
On today's master, 96b05dbbb, also on V1.0.0 tag, test cases fail in case.setup.  Specifically,
```
source /global/project/projectdirs/acme/software/anaconda_envs/cori/base/etc/profile.d/conda.sh; 
conda activate e3sm_unified_1.2.0_py2.7_nox
cd cime/scripts
./create_test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel -p m2833
```
fails with
```
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 386, in run_cmd
            errput = errput.decode('utf-8').strip()
          File "/global/project/projectdirs/acme/software/anaconda_envs/cori/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/encodings/utf_8.py", line 16, in decode
            return codecs.utf_8_decode(input, errors, True)
        UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 77: invalid start byte
```

**Comment by rljacob** [comment]
python error?

**Comment by mark-petersen** [comment]
Yes, python error.  Here is the whole thing:
```
(e3sm_unified_1.2.0_py2.7_nox) edison10:scripts$ ./create_test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel -p m2833
Creating test directory /global/cscratch1/sd/mpeterse/acme_scratch/edison/PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel.20180531_113839_flvcj0
RUNNING TESTS:
  PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel
Starting CREATE_NEWCASE for test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel with 1 procs
Finished CREATE_NEWCASE for test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel in 4.844569 seconds (PASS)
Starting XML for test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel with 1 procs
Finished XML for test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel in 1.057748 seconds (PASS)
Starting SETUP for test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel with 1 procs
Finished SETUP for test PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel in 3.231316 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /global/cscratch1/sd/mpeterse/acme_scratch/edison/PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel.20180531_113839_flvcj0
    Errors were:
        Traceback (most recent call last):
          File "./case.setup", line 56, in <module>
            _main_func(__doc__)
          File "./case.setup", line 53, in _main_func
            case.case_setup(clean=clean, test_mode=test_mode, reset=reset)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 220, in case_setup
            run_and_log_case_status(functor, phase, caseroot=caseroot)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1529, in run_and_log_case_status
            rv = func()
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 214, in <lambda>
            functor = lambda: _case_setup_impl(self, caseroot, clean, test_mode, reset)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 91, in _case_setup_impl
            case.load_env()
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1290, in load_env
            env_module.load_env(self, job=job, verbose=verbose)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_mach_specific.py", line 77, in load_env
            self._load_modules(modules_to_load, force_method=force_method, verbose=verbose)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_mach_specific.py", line 100, in _load_modules
            self._load_module_modules(modules_to_load, verbose=verbose)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/XML/env_mach_specific.py", line 305, in _load_module_modules
            stat, py_module_code, errout = run_cmd(cmd)
          File "/global/u2/m/mpeterse/repos/ACME/update_ocean_ice_shelf_files/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 386, in run_cmd
            errput = errput.decode('utf-8').strip()
          File "/global/project/projectdirs/acme/software/anaconda_envs/cori/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/encodings/utf_8.py", line 16, in decode
            return codecs.utf_8_decode(input, errors, True)
        UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 74: invalid start byte

Due to presence of batch system, create_test will exit before tests are complete.
To force create_test to wait for full completion, use --wait
At test-scheduler close, state is:
FAIL PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel (phase SETUP)
    Case dir: /global/cscratch1/sd/mpeterse/acme_scratch/edison/PET_Ln9.T62_oQU240.GMPAS-IAF.edison_intel.20180531_113839_flvcj0
test-scheduler took 9.69079685211 seconds
```

**Comment by ndkeen** [comment]
I can confirm that `create_test SMS.ne4_ne4.FC5AV1C-L` fails with the errors noted above on edison.  I also tried the same test/repo on Cori and it works.  Edison is just now back from maintenance, but I can't immediately find information about what exactly was maintained.  I do see that the default python version looks like it is new -- though we don't name a python version in our software and I'm not sure what it was before the upgrade.  I tried a few other python modules and I get the same result.

```
edison01% module avail python

-------------------------------------------------------------------------------------------------------------------------------------- /usr/common/software/modulefiles --------------------------------------------------------------------------------------------------------------------------------------
python/2.7-anaconda              python/2.7-anaconda-4.4(default) python/3.5-anaconda              python/3.6-anaconda-4.4
```

**Comment by PeterCaldwell** [comment]
Thanks for the fix, Jim. Do I understand correctly that the model currently won't run on Edison because of the remaining missing module? Whose job is it to fix this - @ndkeen ?

**Comment by rljacob** [comment]
Yes @ndkeen should find what module is now needed.

**Comment by ndkeen** [comment]
OK, I see this was reopened now.  I had just learned that `craype/2.5.12.3` is no longer available.  We should just use `craype/2.5.12`.  I can try it -- I had assume when Jim closed it, he knew it was fixed.

**Comment by ndkeen** [comment]
If I hotfix `cime/scripts/lib/CIME/utils.py` to get around the python error, indeed some of our modules we were using are now missing on edison.  Actually, Jim already pushed those python issues to master.

This branch is first attempt at those new module versions:
`ndk/machinefiles/edison-module-updates-may2018`

**Comment by ndkeen** [comment]
This PR (which modifies versions of modules for edison) is working for me.
https://github.com/E3SM-Project/E3SM/pull/2377

**Comment by jinyun1tang** [comment]
@ndkeen I followed your changes and applied them to my branch on edison. The code then was compiled fine, however, it ended with the error.  Do you have any insights on this?
-------errors are as follows-----------
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.0, library is 1.10.1

**Comment by mark-petersen** [comment]
@xylar is that the same error you saw with MPAS stand alone yesterday?  If so, this may be a larger netcdf/HDF5 issue.

**Comment by xylar** [comment]
Yes, this is the same error I saw.  I then get a crash when the MPAS framework tries to open a NetCDF file, though I'm not sure whether it's for reading or writing.  I'm able to run with the same setup on Cori so I suspect it's an Edison NetCDF or HDF5 issue.

**Comment by jinyun1tang** [comment]
Also to add that I further tried the old version of cray-hdf5, 1.10.0, it compiled fine but crashed during the execution with an pio error and a complain associated with hdf5. So it is very likely an Edison NetCDF compatibility issue with HDF5.

**Comment by xylar** [comment]
I have tried several PIO versions (both 1 and 2) without being able to run standalone MPAS-Ocean.  Unfortunately, I'm not able to document in detail what I did at the moment but if the issue persists, I'm happy to try to dig into it further later this week.

**Comment by rljacob** [comment]
@jayeshkrishna can you look at this?

**Comment by jayeshkrishna** [comment]
Looks like netcdf 4.4.1.1.3 (module: cray-netcdf-hdf5parallel/4.4.1.1.3) depends on hdf5 parallel 1.10.0.3 (module : cray-hdf5-parallel/1.10.0.3) but the hdf5 module loaded by e3sm is for hdf5 parallel 1.10.1.1 (module : cray-hdf5-parallel/1.10.1.1).
The above issue could be due to this mismatch of modules loaded for edison. I haven't tried it yet by switching cray-hdf5-parallel/1.10.1.1 module with cray-hdf5-parallel/1.10.0.3 might fix this issue. @ndkeen, where you able to build+run cases with the changes in PR #2377 on next?

**Comment by ndkeen** [comment]
Of course it built and ran. I don't see any example of something that was tried and failed so that I can try it myself.  One thing that comes to mind is that whatever was tried might not have been completely cleaned.

**Comment by rljacob** [comment]
@xylar and @jinyun1tang, please describe the steps to reproduce the problem you saw.

**Comment by dmricciuto** [comment]
For our CBGC simulations (cc to @susburrows and @acme-y9s), I am getting HDF5 library mismatch errors on edison also.  I am using the CBGC tag with cherry-picked commits from @ndkeen 's PR #2377 .  Runscript is here:  /scratch1/scratchdirs/ricciuto/E3SM_simulations/run_e3sm.20180601.BCRC_1850SPINUP.ne30_oEC.edison.csh

**Comment by jinyun1tang** [comment]
I also tried with SP mode compset I1850CLM45, it worked without any problem. It looks like when BGC is on, the problem occurred. What I did was copying the section for edison from the config_machines.xml by @ndkeen to my file. And then everything else was as conventional.

**Comment by xylar** [comment]
> Looks like netcdf 4.4.1.1.3 (module: cray-netcdf-hdf5parallel/4.4.1.1.3) depends on hdf5 parallel 1.10.0.3 (module : cray-hdf5-parallel/1.10.0.3) but the hdf5 module loaded by e3sm is for hdf5 parallel 1.10.1.1 (module : cray-hdf5-parallel/1.10.1.1).

I'm very happy to report that I got standalone MPAS-O to compile and run on Edison with this change.  It sounds like there's no need for me to document my issue in detail, especially because I wasn't using E3SM directly.  

It looks like #2377 hadn't been updated yet with this change:
https://github.com/E3SM-Project/E3SM/pull/2377/files#diff-3ebd3b4e9be98b41e75a0a8c454492a5R172

@ndkeen, is that intentional?

**Comment by ndkeen** [comment]
Hmmm. I'm not sure how to determine if a specific version of a module depends on a specific version of another module. I was using the following points:

a) cray-netcdf-hdf5parallel/4.4.1.1.3 and cray-hdf5-parallel/1.10.1.1 are the current defaults on the machine.  Which may not mean much, but I would think they were intended to work together.
b) Normally, if module A depends on module B, I would see a warning/error when I try to load module A without module B.  I don't see that.
c) This branch (with modules noted in (a)) seems to be working.

Now, there could easily be a mistake in the way the sys admins installed the modules on the machine (and there could be a way we can work around it).

I haven't yet tried the run script noted above, but I also have not yet tried building "CBGC".

**Comment by ndkeen** [comment]
I ran the run script above. It built the code and submitted a 285-node job. Was the error at runtime?

**Comment by jinyuntang** [comment]
@ndkeen yes, the error was runtime. Also, I tried switching cray-netcdf-hdf5parallel/4.4.1.1.3 with cray-netcdf-hdf5parallel/4.4.1.1.6, which however ended with another error complaining "NetCDF: HDF error" during reading inputs through pio. It is more likely something between hdf5 and netcdf was not installed/configured properly during the update of edison.

**Comment by dmricciuto** [comment]
@ndkeen and @jinyuntang I also tried switching to cray-hdf5-parallel/1.10.0.3 and this didn't work either for the CBGC simulation (failed at runtime).

**Comment by jinyun1tang** [comment]
@ndkeen and @dmricciuto, I also tried with cori-knl, and given the same module configuration used (i.e. cray-hdf5-parallel/1.10.0.3), the run with bgc also failed with identical run-time error.

**Comment by rljacob** [comment]
@ndkeen try SMS.ne30_oECv3.BGCEXP_BCRC_CNPRDCTC_1850.sandiatoss3_intel.clm-bgcexp on your branch for a bgc test.

**Comment by ndkeen** [comment]
I also see this error with the run script provided. To debug I would start by finding a smaller test that repeats the issue. Right now I'm trying something @amametjanov suggested which is to set the following environment variable:
`HDF5_DISABLE_VERSION_CHECK=2`
I'm trying now.

**Comment by ndkeen** [comment]
Setting that environment variable does allow the run to move forward. It ran for over 2 months before timing out. In this case, I added it to config_machines.xml, but you could also add it to a case directory in env_mach_specific.xml.

I don't know if setting this variable is the right way around this issue or not.

My case:
`/global/cscratch1/sd/ndk/E3SM_simulations/20180601.BGCEXP_BCRC_CNPRDCTC_1850SPINUP.ne30np4_oEC60to30v3.edison`

**Comment by xylar** [comment]
I submitted a ticket to NERSC pointing them to this thread. 

My view is that disabling the HDF5 version check is a poor solution to this problem.  It could lead to unexpected model output or crashes that we won't detect in a short model run.  It would be best to find an alternative solution.

Am I right in understanding that a BGC run worked with:
```
HDF5_DISABLE_VERSION_CHECK=2
cray-netcdf-hdf5parallel/4.4.1.1.3
cray-hdf5-parallel/1.10.1.1
```
but not with:
```
cray-netcdf-hdf5parallel/4.4.1.1.3
cray-hdf5-parallel/1.10.0.3
```
?  If so, I think it would be worth trying to get help from NERSC to build a version of cray-netcdf-hdf5parallel that is compatible with `cray-hdf5-parallel/1.10.1.1`.  If not, I would suggest we simply use the latter combination (even though we're not using the default HDF5).

**Comment by ndkeen** [comment]
I don't like the solution either. We should at least get some clarification about what's happening. I have not personally tried what you suggested (using the lower 1.10.1.1 version). I can try that.

**Comment by xylar** [comment]
Here's the response I got from NERSC

> Short description: conflict between default libraries cray-netcdf-hdf5parallel/4.4.1.1.3 and cray-hdf5-parallel/1.10.1.1
Click here to view: INC0121130
Comments:
2018-06-06 10:10:50 PDT - Jialin Liu Additional comments
Hi,
You are correct.
Either way will work.
To force loading 1.10.0.3,
please try:
module load pe_archive
module load cray-hdf5-parallel/1.10.0.3
 
The option: HDF5_DISABLE_VERSION_CHECK=2, is also fine.
Version 1.10.0.3 and 1.10.1.1 have the same file format, but the later fixed a bug in former.
>

>http://www.nersc.gov/users/software/programming-libraries/io-libraries/hdf5/
>
>Best,
>Jialin

**Comment by susburrows** [comment]
@ndkeen , @xylar , thanks for debugging this for us.  This issue is currently preventing progress on the CBGC simulations, and we would like to be making heavy use of NERSC right now to do several tuning simulations (and to use as much of our allocation as possible from the current ALCC allocation year, which ends June 30th).

Although I recognize that it is probably a bad long-term solution, from what you have learned so far, can you advise whether using
HDF5_DISABLE_VERSION_CHECK=2
is a safe workaround in the short term so that we can continue to make progress on the current simulations?

**Comment by xylar** [comment]
NERSC seems to think this is a perfectly fine solution.

**Comment by susburrows** [comment]
OK, thanks @xylar !  ... @dmricciuto can you give this a try in your runscript?

**Comment by ndkeen** [comment]
Thanks for posting the response, I think it helps us to have a group voice when working with NERSC. However, note in the response that what is said is not true. The `pe_archive` module is one of the modules being maintained to help users gain access to older modules. This is something I'm trying out, but it currently doesn't work. To get the  `cray-hdf5-parallel/1.10.0.3` you DO NOT NEED the `pe_archive` module. And loading it might introduce other issues (as I'm finding). 

My job to test out using 1.10.03 is still in the Q.

**Comment by rljacob** [comment]
Do we all agree that its only cases that use BGC data sets that are having trouble?  The e3sm_developer suite passes with what is currently on this branch.

**Comment by jayeshkrishna** [comment]
IMO, Setting HDF5_DISABLE_VERSION_CHECK=1 might be a better option for now (compared to setting it to 2) since we might still get warnings (not abort) about library version mismatch. A better option is to load cray-hdf5-parallel/1.10.0.3 instead.
Also this version check is something that HDF developers need to fix (If two versions have the same ABI typically the version check should not abort the application).

**Comment by dmricciuto** [comment]
Thanks - the HDF5_DISABLE_VERSION_CHECK=2 and cray-hdf5-parallel/1.10.1.1 worked for the CBGC script I am using.  An earlier test I tried using cray-hdf5-parallel/1.10.0.3 didn't work.

**Comment by ndkeen** [comment]
The attempt using 1.10.03 also failed, but with a different error.  I've been seeing this same error and it is in at least one other githib issue. And previous to that, this was the error message that we saw when there was a netcdf file with an old format.

```
   0:  pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         235 :
   0:   NetCDF: HDF error
   0: Image              PC                Routine            Line        Source
   0: e3sm.exe           0000000004A81B68  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000002F77021  pio_support_mp_pi         120  pio_support.F90
   0: e3sm.exe           0000000002F751E2  pio_utils_mp_chec          74  pio_utils.F90
   0: e3sm.exe           000000000307C27A  ionf_mod_mp_open_         235  ionf_mod.F90
   0: e3sm.exe           0000000002F6684F  piolib_mod_mp_pio        2834  piolib_mod.F90
   0: e3sm.exe           000000000054066B  cam_pio_utils_mp_        1111  cam_pio_utils.F90
   0: e3sm.exe           0000000000E1249C  solar_data_mp_sol         160  solar_data.F90
   0: e3sm.exe           000000000060A211  physpkg_mp_phys_i         795  physpkg.F90
   0: e3sm.exe           00000000004FA40E  cam_comp_mp_cam_i         178  cam_comp.F90
   0: e3sm.exe           00000000004EAEF8  atm_comp_mct_mp_a         260  atm_comp_mct.F90
   0: e3sm.exe           0000000000429D78  component_mod_mp_         267  component_mod.F90
   0: e3sm.exe           000000000041942B  cime_comp_mod_mp_        1174  cime_comp_mod.F90
   0: e3sm.exe           0000000000426FB2  MAIN__                     92  cime_driver.F90

```

**Comment by ndkeen** [comment]
Here is case where I ran for 2+ months using the hdf version disable flag.
`/global/cscratch1/sd/ndk/E3SM_simulations/20180601.BGCEXP_BCRC_CNPRDCTC_1850SPINUP.ne30np4_oEC60to30v3.edison`

When I try this same run script using next, it fails. I did have to update the resolution to be `ne30_oECv3` as I know these aliases have changed.  Perhaps it's not yet meant to run with changes in next, but here is the error:

```5407: e3sm.exe           0000000004AC1986  Unknown               Unknown  Unknown
5407: e3sm.exe           0000000004ACD396  Unknown               Unknown  Unknown
5407: e3sm.exe           0000000004387850  Unknown               Unknown  Unknown
5407: e3sm.exe           0000000002D85006  esmf_clockmod_mp_         585  ESMF_ClockMod.F90
5407: e3sm.exe           00000000017C21DB  mpas_timekeeping_         461  mpas_timekeeping.f90
5407: e3sm.exe           0000000001B2600F  mpas_forcing_mp_c         807  mpas_forcing.f90
5407: e3sm.exe           0000000001B2BAD2  mpas_forcing_mp_m         354  mpas_forcing.f90
5407: e3sm.exe           0000000002A67AED  ocn_tracer_ecosys        1824  mpas_ocn_tracer_ecosys.f90
5407: e3sm.exe           0000000002B839FF  ocn_forward_mode_         248  mpas_ocn_forward_mode.f90
5407: e3sm.exe           0000000002A363BA  ocn_core_mp_ocn_c          89  mpas_ocn_core.f90
5407: e3sm.exe           000000000273ED8C  ocn_comp_mct_mp_o         524  ocn_comp_mct.f90
5407: e3sm.exe           000000000042A248  component_mod_mp_         267  component_mod.F90
5407: e3sm.exe           00000000004199B6  cime_comp_mod_mp_        1193  cime_comp_mod.F90
5407: e3sm.exe           0000000000427472  MAIN__                     92  cime_driver.F90

/global/cscratch1/sd/ndk/E3SM_simulations/next-jun7.BGCEXP_BCRC_CNPRDCTC_1850SPINUP.ne30_oECv3.edison
```
