### ISSUE TITLE
GMPAS-DIB-IAF.T62_oRRS30to10v3wLI sporadically failing during namelist generation on Theta

### ISSUE THREAD

**Issue by darincomeau** [E3SM-Project/E3SM#2802]
A simulation with the compset/grid GMPAS-DIB-IAF.T62_oRRS30to10v3wLI is sporadically failing during job resubmission in during namelist generation. The error is not reproducible, and a subsequently resubmitting the job seems to get past the error. The component for which namelist generation fails is not consistent (once in datm, once in mpas-ocean).

Sample from the output log:
```
2019-03-13 12:56:06 CASE.RUN BEGINS HERE
2019-03-13 12:56:06 RUN_MODEL BEGINS HERE
2019-03-13 12:56:06 PRE_RUN_CHECK BEGINS HERE
2019-03-13 12:56:07 NAMELIST CREATION BEGINS HERE
Generating namelists for /projects/OceanClimate_2/sprice/e3sm-cases/20190301.GMPAS-DIB-IAF.T62_oRRS30to10v3wLI.theta
Creating component namelists
  2019-03-13 12:56:07 atm
   Calling /lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/src/components/data_comps/datm/cime_config/buildnml
  2019-03-13 12:56:08 lnd
   Calling /lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/src/components/stub_comps/slnd/cime_config/buildnml
  2019-03-13 12:56:08 ice
   Calling /lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/components/mpas-seaice/cime_config/buildnml
  2019-03-13 12:56:08 ocn
   Calling /lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/components/mpas-ocean/cime_config/buildnml
```

From the error log:
```
Traceback (most recent call last):
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-cases/20190301.GMPAS-DIB-IAF.T62_oRRS30to10v3wLI.theta/.case.run", line 81, in <module>
    _main_func(__doc__)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-cases/20190301.GMPAS-DIB-IAF.T62_oRRS30to10v3wLI.theta/.case.run", line 76, in _main_func
    success = case.case_run(skip_pnl=skip_pnl, set_continue_run=set_continue_run, submit_resubmits=resubmit)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 296, in case_run
    lid = _run_model(self, lid, skip_pnl, da_cycle=cycle)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 160, in _run_model
    return run_and_log_case_status(functor, "case.run", caseroot=case.get_value("CASEROOT"))
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1691, in run_and_log_case_status
    rv = func()
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 159, in <lambda>
    functor = lambda: _run_model_impl(case, lid, skip_pnl=skip_pnl, da_cycle=da_cycle)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 73, in _run_model_impl
    _pre_run_check(case, lid, skip_pnl=skip_pnl, da_cycle=da_cycle)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_run.py", line 58, in _pre_run_check
    case.create_namelists()
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 87, in create_namelists
    run_sub_or_cmd(cmd, (caseroot), "buildnml", (self, caseroot, compname), case=self)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 371, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/components/mpas-ocean/cime_config/buildnml", line 300, in buildnml
    safe_copy(os.path.join(mpasoconf_dir, "mpaso_in"), os.path.join(rundir, in_filename))
  File "/lus/theta-fs0/projects/OceanClimate_2/sprice/e3sm-repo/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 826, in safe_copy
    shutil.copy2(src_path, tgt_path)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
IOError: [Errno 5] Input/output error
```

**Comment by amametjanov** [comment]
Namelist generation is done during job launch on a couple of `MOM` nodes on Theta. The load on MOM nodes may vary depending on how many jobs are being launched at any one time. I think this could be the reason for sporadic errors.

If the namelists do not change between resubmissions, a workaround is to submit a job with
```
$ ./case.submit --skip-preview-namelist
```
which should reuse previously generated component namelists.

Email notifications on job start and end can also help track progress: e.g.
```
$ cat ~/.cime/config
[main]
CIME_MODEL=e3sm
MAIL_USER=azamat@anl.gov
MAIL_TYPE=all
```

**Comment by darincomeau** [comment]
@jgfouca , @amametjanov , do you mind taking a look at this issue we're having on Theta? It seems to be either a cime or filesystem issue, and is preventing us from running these simulations.

cc: @stephenprice , @jonbob

**Comment by jgfouca** [comment]
@darincomeau , that's a strange error. Google seems to suggest it's a python bug. What python version are you using? Would it be possible to try a newer one (3.5+)?

**Comment by darincomeau** [comment]
Thanks @amametjanov , that sounds like a good workaround. I'm assuming ```./case.submit --skip-preview-namelist``` would only apply to the original submission, and not any resubmits? Is there a way to get ```--skip-preview-namelist``` to stick for resubmits?

**Comment by amametjanov** [comment]
Yes, it should stick to resubmits too.

**Comment by stephenprice** [comment]
Thanks @amametjanov. I was finally able to confirm this worked (at least it worked for a single re-submit). Trying now with a larger no. of resubmits. 

I'm not sure if we should close this issue now or leave open until there's a more permanent fix?

**Comment by stephenprice** [comment]
Not clear why, but for some reason the job that I submitted on Theta several days ago is still sitting in the queue. So unfortunately no update on this yet.

**Comment by stephenprice** [comment]
Not clear why, but for some reason the job that I submitted on Theta several days ago is still sitting in the queue. So unfortunately no update on this yet.

Actually, this is working again (the queuing I was seeing were the resubmits waiting -- it has now progressed through 9 resubmits).

So I would say this IS working now. But I'm still not clear if we should be looking for a more permanent solution for this problem or not.

**Comment by amametjanov** [comment]
Great!

CIME depends on python as a pre-requisite. I'm not sure if switching python version through a machine-specific module (in env_mach_specific.xml or smth similar) is recommended. So to try out @jgfouca's suggestion is to load newer python in a login shell dot file: e.g. in `~/.bash_profile`:
```
if [[ $HOSTNAME == theta* ]]; then
  module load cray-python/3.6.1.1
fi
```

Default version on Theta is
```
$ which python
/usr/bin/python
$ python --version
Python 2.7.13
```

**Comment by stephenprice** [comment]
Thanks @amametjanov. I can try that too. 

@xylar, let me know if you have any thoughts on this since you are much more familiar with python environments / versions than me.

**Comment by xylar** [comment]
@stephenprice, if there's an environment or version conflict, it sounds like something specific to CIME so I can't offer any expertise on that.  @amametjanov's advice sounds perfectly reasonable to me.  You'll need to load `e3sm-unified` for analysis but that's a separate issue from which python you use for CIME.

**Comment by darincomeau** [comment]
Closing this as outdated.
