### ISSUE TITLE
Attempting single-site run - missing lai_streams from https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/

### ISSUE THREAD

**Issue by serbinsh** [E3SM-Project/E3SM#2813]
I am attempting to conduct a test single-site run: https://github.com/serbinsh/elm_containers/blob/master/elm_run_scripts/create_case_1pt_example_USNR1.sh

But getting these errors:

```
Finished creating component namelists
Checking that inputdata is available as part of case submission
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/datm.input_data_list'
Loading input file list: 'Buildconf/mosart.input_data_list'
Loading input file list: 'Buildconf/clm.input_data_list'
  Model clm missing file stream_fldfilename_lai = '/data//lnd/clm2/lai_streams/MODISPFTLAI_0.5x0.5_c140711.nc'
Model clm no file specified for finidat
Checking server https://web.lcrc.anl.gov/public/e3sm/inputdata/ with protocol wget
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/datm.input_data_list'
Loading input file list: 'Buildconf/mosart.input_data_list'
Loading input file list: 'Buildconf/clm.input_data_list'
  Model clm missing file stream_fldfilename_lai = '/data//lnd/clm2/lai_streams/MODISPFTLAI_0.5x0.5_c140711.nc'
FAIL: Repo 'https://web.lcrc.anl.gov/public/e3sm/inputdata/' does not have file 'https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/lai_streams/MODISPFTLAI_0.5x0.5_c140711.nc'
Reason:
Spider mode enabled. Check if remote file exists.
--2019-03-21 14:38:38--  https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/lai_streams/MODISPFTLAI_0.5x0.5_c140711.nc
Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.74.23
Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.74.23|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!

Model clm no file specified for finidat
Checking server https://acme-svn2.ornl.gov/acme-repo/acme/inputdata with protocol svn

Could not connect to svn repo 'https://acme-svn2.ornl.gov/acme-repo/acme/inputdata'
This is most likely either a credential, proxy, or network issue .
To check connection and store your credential run 'svn ls https://acme-svn2.ornl.gov/acme-repo/acme/inputdata' and permanently store your password
Loading input file list: 'Buildconf/cpl.input_data_list'
Loading input file list: 'Buildconf/datm.input_data_list'
Loading input file list: 'Buildconf/mosart.input_data_list'
Loading input file list: 'Buildconf/clm.input_data_list'
  Model clm missing file stream_fldfilename_lai = '/data//lnd/clm2/lai_streams/MODISPFTLAI_0.5x0.5_c140711.nc'
Traceback (most recent call last):
  File "./case.submit", line 108, in <module>
    _main_func(__doc__)
  File "./case.submit", line 105, in _main_func
    mail_user=mail_user, mail_type=mail_type, batch_args=batch_args)
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 156, in submit
    custom_success_msg_functor=verbatim_success_msg)
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1634, in run_and_log_case_status
    rv = func()
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 154, in <lambda>
    batch_args=batch_args)
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 84, in _submit
    case.check_case()
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 170, in check_case
    self.check_all_input_data()
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 50, in check_all_input_data
    success = _downloadfromserver(self, input_data_root, data_list_dir)
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 65, in _downloadfromserver
    input_data_root=input_data_root, data_list_dir=data_list_dir)
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 209, in check_input_data
    isdirectory=rel_path.endswith(os.sep))
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 17, in _download_if_in_repo
    if not server.fileexists(rel_path):
  File "/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/Servers/svn.py", line 29, in fileexists
    full_url = os.path.join(self._svn_loc, rel_path)
AttributeError: 'SVN' object has no attribute '_svn_loc'
```

Looks like https://web.lcrc.anl.gov/public/e3sm/inputdata/lnd/clm2/lai_streams/ is empty.  Not sure if that is a bug or feature and I can also try a different compset perhaps.

Apologies if this is a "user error"

**Comment by bishtgautam** [comment]
If the data is unavailable at ANL and ORNL server, the script is suppose to look for the missing data at NCAR's svn server. You can manually download the missing data from NCAR's svn server at:
https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/lnd/clm2/lai_streams/

**Comment by rljacob** [comment]
@jgfouca that last error message looks odd.  
@serbinsh you should try latest master where we removed the no-longer active ORNL server.

**Comment by rljacob** [comment]
This error came up here:
https://github.com/ESMCI/cime/issues/2678
In your case, you could remove the ornl entry from E3SM/cime/config/e3sm/config_inputdata.xml

**Comment by jgfouca** [comment]
Fixed this a while ago.
