### ISSUE TITLE
InvalidHeaderError: invalid header, lib error or archive error?

### ISSUE THREAD

**Issue by chengdang** [E3SM-Project/E3SM#2845]
Hello, I'm trying to extract some files using zstash on NERSC:

zstash extract --hpss=/home/g/golaz/2018/E3SM_simulations/repaired/20180129.DECKv1b_piControl.ne30_oEC.edison archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.00[2-3][0-9]-[0-1][0-9]-01.nc

I got numerous errors as follows:

```
...
INFO: Extracting archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-06-01.nc
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/zstash/extract.py", line 129, in extractFiles
    tarinfo = tar.tarinfo.fromtarfile(tar)
  File "/global/homes/c/cdang/.conda/envs/zstash_env/lib/python2.7/tarfile.py", line 1252, in fromtarfile
    obj = cls.frombuf(buf)
  File "/global/homes/c/cdang/.conda/envs/zstash_env/lib/python2.7/tarfile.py", line 1211, in frombuf
    chksum = nti(buf[148:156])
  File "/global/homes/c/cdang/.conda/envs/zstash_env/lib/python2.7/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
InvalidHeaderError: invalid header
ERROR: Retrieving archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-06-01.nc
....


ERROR: Encountered an error for files:
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-01-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-02-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-03-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-04-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-05-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-06-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-07-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-08-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-09-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-10-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-11-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0020-12-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-01-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-02-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-03-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-04-01.nc in 00001d.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-05-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-06-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-07-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-08-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-09-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-10-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-11-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0021-12-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-01-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-02-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-03-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-04-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-05-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-06-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-07-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-08-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-09-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-10-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-11-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0022-12-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-01-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-02-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-03-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-04-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-05-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-06-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-07-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-08-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-09-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-10-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-11-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0023-12-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-01-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-02-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-03-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-04-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-05-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-06-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-07-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-08-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-09-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-10-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-11-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0024-12-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-01-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-02-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-03-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-04-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-05-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-06-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-07-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-08-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-09-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-10-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-11-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0025-12-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-01-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-02-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-03-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-04-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-05-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-06-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-07-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-08-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-09-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-10-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-11-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0026-12-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-01-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-02-01.nc in 00001e.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-03-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-04-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-05-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-06-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-07-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-08-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-09-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-10-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-11-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0027-12-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-01-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-02-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-03-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-04-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-05-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-06-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-07-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-08-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-09-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-10-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-11-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0028-12-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-01-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-02-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-03-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-04-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-05-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-06-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-07-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-08-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-09-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-10-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-11-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0029-12-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-01-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-02-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-03-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-04-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-05-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-06-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-07-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-08-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-09-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-10-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-11-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0030-12-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-01-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-02-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-03-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-04-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-05-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-06-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-07-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-08-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-09-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-10-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-11-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0031-12-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-01-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-02-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-03-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-04-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-05-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-06-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-07-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-08-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-09-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-10-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-11-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0032-12-01.nc in 00001f.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-01-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-02-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-03-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-04-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-05-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-06-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-07-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-08-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-09-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-10-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-11-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0033-12-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-01-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-02-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-03-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-04-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-05-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-06-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-07-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-08-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-09-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-10-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-11-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0034-12-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-01-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-02-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-03-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-04-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-05-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-06-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-07-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-08-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-09-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-10-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-11-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0035-12-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-01-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-02-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-03-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-04-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-05-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-06-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-07-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-08-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-09-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-10-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-11-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0036-12-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-01-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-02-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-03-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-04-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-05-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-06-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-07-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-08-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-09-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-10-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-11-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0037-12-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-01-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-02-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-03-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-04-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-05-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-06-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-07-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-08-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-09-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-10-01.nc in 000020.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-11-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0038-12-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-01-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-02-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-03-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-04-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-05-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-06-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-07-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-08-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-09-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-10-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-11-01.nc in 000021.tar
ERROR: archive/ocn/hist/mpaso.hist.am.timeSeriesStatsMonthly.0039-12-01.nc in 000021.tar
ERROR: The following tar archives had errors:
ERROR: 00001d.tar
ERROR: 00001e.tar
ERROR: 00001f.tar
ERROR: 000020.tar
ERROR: 000021.tar


```

Does this mean the tar files archived on HPSS contain errors? or is this a hidden python lib error? 
Any suggestion on how to fix this? Thanks.

**Comment by tangq** [comment]
Try add "" to the files.

**Comment by chengdang** [comment]
@tangq thanks, Qi. It returns the same errors. BTW, I am able to extract ice and atm outputs, somehow not the ocean outputs.

**Comment by tangq** [comment]
A few other things you can try.
- delete the zstash/index.db file and retrieve a new one
- check the file list (`zstash ls`) to see if the files exist
- use a different way to match the file names

**Comment by chengdang** [comment]
@tangq  thanks Qi. I fixed it by deleting the existing index.db and retrieve a new one. I'll close this question.
