### ISSUE TITLE
svn error on maint-1.0

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2931]
While trying to build the water cycle case on maint-1.0, I made a mistake and had the wrong refcase.   Since it couldn't find the refcase, it tried to download it (I think) and triggered an svn error.

```
Loading input file list: 'Buildconf/refcase.input_data_list'
  Model refcase missing file refdir = '/project/projectdirs/acme/inputdata/e3sm_init/20171228.beta3rc13_1850.ne30_oECv3_ICG.cori-knl/0331-01-01/'
Traceback (most recent call last):
  File "/global/cscratch1/sd/rjacob/E3SM_simulations/20180420.DECKv1b_piControl.ne30_oEC.cori-knl/case_scripts/case.submit", line 75, in <module>
    _main_func(__doc__)
  File "/global/cscratch1/sd/rjacob/E3SM_simulations/20180420.DECKv1b_piControl.ne30_oEC.cori-knl/case_scripts/case.submit", line 72, in _main_func
    batch_args=batch_args)
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 123, in submit
    custom_success_msg_functor=verbatim_success_msg)
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1529, in run_and_log_case_status
    rv = func()
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 121, in <lambda>
    batch_args=batch_args)
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 74, in _submit
    case.check_case()
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/case_submit.py", line 135, in check_case
    self.create_namelists() # Must be called before check_all_input_data
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 61, in create_namelists
    self.stage_refcase()
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 98, in stage_refcase
    success = _downloadfromserver(self, input_data_root=input_data_root, data_list_dir=data_list_dir)
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 65, in _downloadfromserver
    input_data_root=input_data_root, data_list_dir=data_list_dir)
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 209, in check_input_data
    isdirectory=rel_path.endswith(os.sep))
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 17, in _download_if_in_repo
    if not server.fileexists(rel_path):
  File "/global/u2/r/rjacob/E3SM_code/20180420/cime/scripts/Tools/../../scripts/lib/CIME/Servers/svn.py", line 29, in fileexists
    full_url = os.path.join(self._svn_loc, rel_path)
AttributeError: 'SVN' object has no attribute '_svn_loc'
```

**Comment by jgfouca** [comment]
@rljacob , you must be using an ancient version of CIME if it's trying to use SVN.

**Comment by rljacob** [comment]
Yes the maint-1.0 version dates back to April of last year.

**Comment by jgfouca** [comment]
Some config files probably need to be updated so that it uses http.

**Comment by rljacob** [comment]
Sure we can just remove the svn options.  But it looks like it was trying svn and had some deeper error.

**Comment by jgfouca** [comment]
Yeah, there was a python mistake that has also since been fixed.

**Comment by rljacob** [comment]
Fixed by removing the ornl svn server.

**Comment by jgfouca** [comment]
Fixed on maint.
