### ISSUE TITLE
create_test error in maint-1.1

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3427]
I'm trying to run create_test on one of the production cases.  Its a hybrid case and something is going wrong.  This is on compy using the head of maint-1.1.
```
[jaco316@compy-e scripts]$ ./create_test --no-build SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6
Using project from env PROJECT: e3sm
Creating test directory /compyfs/jaco316/e3sm_scratch/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6.20200204_115638_5w9g8j
RUNNING TESTS:
  SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6
Starting CREATE_NEWCASE for test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 with 1 procs
Finished CREATE_NEWCASE for test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 in 3.057589 seconds (PASS)
Starting XML for test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 with 1 procs
Finished XML for test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 in 0.516140 seconds (PASS)
Starting SETUP for test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 with 1 procs
Finished SETUP for test SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 in 1.099709 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /compyfs/jaco316/e3sm_scratch/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6.20200204_115638_5w9g8j
    Errors were:
        /compyfs/jaco316/e3sm_scratch/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6.20200204_115638_5w9g8j/env_mach_specific.xml already exists, delete to replace
        Traceback (most recent call last):
          File "./case.setup", line 62, in <module>
            _main_func(__doc__)
          File "./case.setup", line 59, in _main_func
            case.case_setup(clean=clean, test_mode=test_mode, reset=reset)
          File "/qfs/people/jaco316/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 225, in case_setup
            run_and_log_case_status(functor, phase, caseroot=caseroot)
          File "/qfs/people/jaco316/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1634, in run_and_log_case_status
            rv = func()
          File "/qfs/people/jaco316/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 219, in <lambda>
            functor = lambda: _case_setup_impl(self, caseroot, clean, test_mode, reset)
          File "/qfs/people/jaco316/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/case_setup.py", line 203, in _case_setup_impl
            case.create_namelists()
          File "/qfs/people/jaco316/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 61, in create_namelists
            self.stage_refcase()
          File "/qfs/people/jaco316/E3SM/cime/scripts/Tools/../../scripts/lib/CIME/case/check_input_data.py", line 112, in stage_refcase
            shutil.copy2(rpointerfile, rundir)
        NameError: global name 'shutil' is not defined

At test-scheduler close, state is:
FAIL SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6 (phase SETUP)
    Case dir: /compyfs/jaco316/e3sm_scratch/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6.20200204_115638_5w9g8j
test-scheduler took 4.95992898941 seconds

```

The first problem is this complaint:  

`/compyfs/jaco316/e3sm_scratch/SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel.allactive-v1cmip6.20200204_115638_5w9g8j/env_mach_specific.xml already exists, delete to replace`

But that directory did not exist.   The create_test command made it.

Second issue is this message:
```
            shutil.copy2(rpointerfile, rundir)
        NameError: global name 'shutil' is not defined
```

I'm using python 2.7.5

**Comment by jgfouca** [comment]
Fixed by #3428
