### ISSUE TITLE
SMS_D_Ld4.f45_f45.IELMED ERROR: Attempt to fetch from allocatable variable HLM_HARVEST_RATES when it is not allocated

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3952]
With a master of Nov 3rd and Nov 19th, I was trying `SMS_D_Ld4.f45_f45.IELMED` to help a user diagnosis issue and run into this:

```
5: forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable HLM_HARVEST_RATES when it is not allocated
5:
5: Image              PC                Routine            Line        Source
5: e3sm.exe           00000000069E0B16  Unknown               Unknown  Unknown
5: e3sm.exe           00000000039DFE38  edpatchdynamicsmo         214  EDPatchDynamicsMod.F90
5: e3sm.exe           00000000033D024C  edmainmod_mp_ed_e         182  EDMainMod.F90
5: e3sm.exe           0000000000A264A8  clmfatesinterface         757  clmfates_interfaceMod.F90
5: e3sm.exe           00000000008F6E5A  clm_driver_mp_clm        1185  clm_driver.F90
5: e3sm.exe           000000000088837F  lnd_comp_mct_mp_l         501  lnd_comp_mct.F90
5: e3sm.exe           000000000046283D  component_mod_mp_         737  component_mod.F90
5: e3sm.exe           0000000000429DE9  cime_comp_mod_mp_        2700  cime_comp_mod.F90
5: e3sm.exe           000000000044A330  MAIN__                    153  cime_driver.F90
5: e3sm.exe           0000000000401AE2  Unknown               Unknown  Unknown
5: e3sm.exe           0000000006AD1A8F  Unknown               Unknown  Unknown
5: e3sm.exe           00000000004019CA  Unknown               Unknown  Unknown
```

**Comment by ndkeen** [comment]
Using GNU and DEBUG, I see a different error which may or may not be related to above. 

```
SMS_D_Ld1.f45_f45.IELMED.cori-knl_gnu

4: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
4:
4: Backtrace for this error:
4: #0  0x265a0ff in ???
4:      at /home/abuild/rpmbuild/BUILD/glibc-2.26/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
4: #1  0x1625668 in __fateshistoryinterfacemod_MOD_update_history_prod
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/components/elm/src/external_models/fates/main/FatesHistoryInterfaceMod.F90:3356
4: #2  0x6c93a8 in __clmfatesinterfacemod_MOD_wrap_accumulatefluxes
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/components/elm/src/main/clmfates_interfaceMod.F90:1895
4: #3  0xce3e0f in __canopyfluxesmod_MOD_canopyfluxes
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/components/elm/src/biogeophys/CanopyFluxesMod.F90:1240
4: #4  0x61ef08 in __clm_driver_MOD_clm_drv
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/components/elm/src/main/clm_driver.F90:686
4: #5  0x5fb76d in __lnd_comp_mct_MOD_lnd_run_mct
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/components/elm/src/cpl/lnd_comp_mct.F90:501
4: #6  0x438e19 in __component_mod_MOD_component_run
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/cime/src/drivers/mct/main/component_mod.F90:714
4: #7  0x41608c in __cime_comp_mod_MOD_cime_run
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/cime/src/drivers/mct/main/cime_comp_mod.F90:2705
4: #8  0x436238 in cime_driver
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/cime/src/drivers/mct/main/cime_driver.F90:153
4: #9  0x4362a2 in main
4:      at /global/cscratch1/sd/ndk/wacmy/m49-nov19/cime/src/drivers/mct/main/cime_driver.F90:23
```

**Comment by ndkeen** [comment]
As the IELMED compset is no longer available, I will close this issue. However, I tested with IELMFATES and see a different fail.
