### ISSUE TITLE
Error with GNU on cori-knl using SMS_D_Ln5.ne4_ne4.FC5AV1C-L (double free or corruption)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4249]
I tried `e3sm_developer` with GNU using latest master and other than several ERS compare fails (which have an issue), the only other failure was `SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_gnu`.

I found this same error in a closed issue (https://github.com/E3SM-Project/E3SM/issues/3270), but it's not clear if it was fixed.

```
26: *** Error in `/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl.mfP5/SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_gnu.20210422_220519_plj8se/bld/e3sm.exe': double free or corruption (!prev): 0x000000001baf0670 ***
26: 
26: Program received signal SIGABRT: Process abort signal.
26: 
26: Backtrace for this error:
26: #0  0x46962cf in ???
26:     at /home/abuild/rpmbuild/BUILD/glibc-2.26/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
26: #1  0x7cd7900 in raise
26:     at ../sysdeps/unix/sysv/linux/raise.c:51
26: #2  0x7d82dd0 in abort
26:     at /home/abuild/rpmbuild/BUILD/glibc-2.26/stdlib/abort.c:79
26: #3  0x7da24f6 in __libc_message
26:     at ../sysdeps/posix/libc_fatal.c:181
26: #4  0x7da8962 in malloc_printerr
26:     at /home/abuild/rpmbuild/BUILD/glibc-2.26/malloc/malloc.c:5428
26: #5  0x7daa210 in _int_free
26:     at /home/abuild/rpmbuild/BUILD/glibc-2.26/malloc/malloc.c:4170
26: #6  0x2c571a1 in __soiltemperaturemod_MOD_setrhsvec
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/components/elm/src/biogeophys/SoilTemperatureMod.F90:2087
26: #7  0x2c8b7fb in __soiltemperaturemod_MOD_solvetemperature
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/components/elm/src/biogeophys/SoilTemperatureMod.F90:796
26: #8  0x2c999a3 in __soiltemperaturemod_MOD_soiltemperature
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/components/elm/src/biogeophys/SoilTemperatureMod.F90:526
26: #9  0x22ed249 in __elm_driver_MOD_elm_drv._omp_fn.4
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/components/elm/src/main/elm_driver.F90:1324
26: #10  0x7cd808e in GOMP_parallel
26:     at ../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libgomp/parallel.c:168
26: #11  0x22e4fa2 in __elm_driver_MOD_elm_drv
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/components/elm/src/main/elm_driver.F90:1324
26: #12  0x22b886d in __lnd_comp_mct_MOD_lnd_run_mct
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/components/elm/src/cpl/lnd_comp_mct.F90:501
26: #13  0x446955 in __component_mod_MOD_component_run
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/driver-mct/main/component_mod.F90:714
26: #14  0x420e53 in __cime_comp_mod_MOD_cime_run
26:     at /global/cscratch1/sd/ndk/wacmy/ndk_machinefiles_cori-add-PERL5LIB/driver-mct/main/cime_comp_mod.F90:2860
26: #15  0x443d74 in cime_driver

```

Works with same test on cori-haswell

**Comment by ndkeen** [comment]
Unable to repeat this issue using current master. Also tried gnu9 and gnu10.
