### ISSUE TITLE
Problem with provenance on Theta

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4461]
We do a `qstat -l` during runtime and this is failing on Theta which causes a runtime failure.

```
thetalogin6% qstat -l
...
*** FATAL EXCEPTION: 'ascii' codec can't encode character u'\u2013' in position 82: ordinal not in range(128) ***
Traceback (most recent call last):
  File "/usr/libexec/cobalt/bin/qstat.py", line 304, in <module>
    main()
  File "/usr/libexec/cobalt/bin/qstat.py", line 300, in main
    process_the_output(output,parser,hinfo)
  File "/usr/libexec/cobalt/bin/qstat.py", line 257, in process_the_output
    client_utils.print_vertical([tuple(x) for x in [hinfo.header] + output])
  File "/usr/lib64/python2.7/site-packages/Cobalt/client_utils.py", line 411, in print_vertical
    Cobalt.Util.print_vertical(rows)
  File "/usr/lib64/python2.7/site-packages/Cobalt/Util.py", line 487, in print_vertical
    print hformat % (rows[0][x], row[x])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 82: ordinal not in range(128)
```

In general, I think we should minimize what happens on the compute nodes, but when something besides e3sm.exe does run, at least don't cause the run to fail.

I'm working around my setting SAVE_TIMING=FALSE.

**Comment by worleyph** [comment]
Just tried 

> qstat -l

from thetalogin5 and it worked fined.

> In general, I think we should minimize what happens on the compute nodes, but when something besides e3sm.exe does run, at least don't cause the run to fail.

When a system commands fails with a fatal exception not sure how we can catch this and do anything reasonable. Better to report the failure to the system admins?

**Comment by worleyph** [comment]
And this is in the batch job script, but not on the compute nodes?

**Comment by ndkeen** [comment]
OK, I now see that the flags to qstat are also important.  This is actual command that failed:

`qstat -l --header JobID:JobName:User:Project:WallTime:QueuedTime:Score:RunTime:TimeRemaining:Nodes:State:Location:Mode:Command:Args:Procs:Queue`

I still say we are doing too much on the compute nodes.  If a run is sitting in the Q for many days and fails because of this, that would be unfortunate.

**Comment by worleyph** [comment]
Did not run on the compute nodes. Just ran on the front end. 

Just tried the above command on thetalogin4, and it also worked for me.

**Comment by worleyph** [comment]
Perhaps the issue is that testing on Theta always has SAVE_TIMING=FALSE., so system issues are missed? If the problem is only apparent on one login node, not sure how to defend against this.

**Comment by ndkeen** [comment]
Ah, could be as I just tried a simple test which is working.  Here is the case that failed:
`/projects/ClimateEnergy_4/ndkeen/SCREAMv010.SCREAM-DY2.ne256pg2.jul13.n0256a32x411141.spa.cosp`

But I still see the error when I try the qstat command from login node.  I logged in again and see the same thing (but landed on same node)

**Comment by worleyph** [comment]
I've tried every qstat call in the syslog command and in CIME (in provenance.py), and they all work for me (on the node that I am on now).

**Comment by worleyph** [comment]
It looks like the background progress monitoring job (mach_syslog)  is the one that failed, which surprises me that it killed the batch script. In the past this has failed (for other reasons) and had no impact on the model run. Perhaps because a system command failed, or maybe launching from python is different (since qstat is itself a python job).

You can also just replace mach_syslog in the Tools subdirectory by E3SM/cime_config/machines/syslog.noop and not disable all provenance collection. However, without mach_syslog you lose most of the checkpoint data. 

Again, this seems to be a specific login node issue. I suggest submitting a ticket (after verifying that you can get the command to work on other login nodes). Don't trust my success. Maybe something is different in our experiments or environments.

**Comment by worleyph** [comment]
@ndkeen , I'm confused. Base on timestamps, it looks like the E3SM job still running. What is the LID for the failed job. Maybe the background did fail without impacting the E3SM run? If the job died before generating any model logs, then it may not be the background job, but rather the call in provenance.py . How did you determine the arguments in the failed qstat call?

**Comment by ndkeen** [comment]
I tried a different login node and still see the error.

The job is running (just completed) as I turned off SAVE_TIMING. To see the fails, try:  

```
540950.error and 540966.error

540950.error:ERROR: Command: 'qstat -l --header JobID:JobName:User:Project:WallTime:QueuedTime:Score:RunTime:TimeRemaining:Nodes:State:Location:Mode:Command:Args:Procs:Queue:StartTime:attrs:Geometry' failed with error '*** FATAL EXCEPTION: 'ascii' codec can't encode character u'\u2013' in position 83: ordinal not in range(128) ***
540966.error:ERROR: Command: 'qstat -l --header JobID:JobName:User:Project:WallTime:QueuedTime:Score:RunTime:TimeRemaining:Nodes:State:Location:Mode:Command:Args:Procs:Queue:StartTime:attrs:Geometry' failed with error '*** FATAL EXCEPTION: 'ascii' codec can't encode character u'\u2013' in position 83: ordinal not in range(128) ***
```

In python, we use routine that will not fail if the unix command fails. Can we do the same for wherever this is coming from?

**Comment by worleyph** [comment]
I still do not see a failure when I try this command. I'm using /bin/tcsh. What is your shell? (SHouldn't matter, but ...).

Looking at 540950.output, this is dying in the call within provenance.py . @jgfouca  will have to comment on whether this would be easy to catch an exception and not kill the job when qstat fails. Though, again, qstat should not fail.

**Comment by worleyph** [comment]
Worked for me on thetalogin4, thetalogin5, and thetalogin6 .

**Comment by worleyph** [comment]
Changed shell to bash, and still works for me.

**Comment by ndkeen** [comment]
I tried again today and it is working again -- both the command on a login node as well as a test case with SAVE_TIMING.
