### ISSUE TITLE
SIGFPE: Floating-point exception with SMS_D_Ln5.ne4_oQU240.F2010 using "invalid" check

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4596]
With SMS_D_Ln5.ne4_oQU240.F2010 (and gnu9 in this case), I added the "invalid" trap for GNU (ie `-ffpe-trap=invalid,zero,overflow`) and hit:

```
 8: 
 8: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
 8: 
 8: Backtrace for this error:
 8: #0  0x7fe10a6ca49f in ???
 8: #1  0x45222a8 in mosart_init
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/components/mosart/src/riverroute/RtmMod.F90:4171
 8: #2  0x4580df4 in __rtmmod_MOD_rtmini
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/components/mosart/src/riverroute/RtmMod.F90:1777
 8: #3  0x44ea64e in __rof_comp_mct_MOD_rof_init_mct
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/components/mosart/src/cpl/rof_comp_mct.F90:294
 8: #4  0x44397a in __component_mod_MOD_component_init_cc
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/driver-mct/main/component_mod.F90:248
 8: #5  0x42b9c4 in __cime_comp_mod_MOD_cime_init
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/driver-mct/main/cime_comp_mod.F90:1437
 8: #6  0x43cbab in cime_driver
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/driver-mct/main/cime_driver.F90:122
 8: #7  0x43cceb in main
 8:     at /pscratch/sd/n/ndk/wacmy/m02-oct5/driver-mct/main/cime_driver.F90:23
```

I think the issue here is that this line:

```
 if(TUnit%tlen(iunit) > 0._r8 .and. (TUnit%rlenTotal(iunit)-TUnit%rlen(iunit))/TUnit%tlen(iunit) > 1._r8) then
```

is not good practice -- the value `TUnit%tlen(iunit)` is indeed 0.0 -- and it's quite possible that both branches here will be evaluated -- hence a div-by-zero. Would need to test for zero on a separate line, I think.

As a quick test, I did try placing the check for 0 on separate line and the smoke test completed with no other issues.

**Comment by hydrotian** [comment]
Thanks. I will issue a PR to fix this bug.
