### ISSUE TITLE
Array index overflow in ERS.r05_r05.IELM.elm-V2_ELM_MOSART_features

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#4727]
This fails on Ascent with GNU compiler. While looking into why with debug flags, I saw that it fails on Summit and Chrysalis too: e.g.
```
./cime/scripts/create_test ERS_D_P128x1.r05_r05.IELM.chrysalis_gnu.elm-V2_ELM_MOSART_features --compiler gnu
```
Initial run encounters:
```
113:  (WRM_init)Done with WM init ...
113: At line 607 of file /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/mosart/src/wrm/WRM_modules.F90
113: Fortran runtime error: Index '-99' of dimension 1 of array 'wrmunit%meanmthflow' below lower bound of 1
113:
113: Error termination. Backtrace:
113: #0  0x1e5b865 in __wrm_modules_MOD_regulation
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/mosart/src/wrm/WRM_modules.F90:607
113: #1  0x1df0412 in __mosart_physics_mod_MOD_euler
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/mosart/src/riverroute/MOSART_physics_mod.F90:445
113: #2  0x1d11bea in __rtmmod_MOD_rtmrun
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/mosart/src/riverroute/RtmMod.F90:2464
113: #3  0x1cc93c3 in __rof_comp_mct_MOD_rof_run_mct
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/mosart/src/cpl/rof_comp_mct.F90:357
113: #4  0x43d9af in __component_mod_MOD_component_run
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/component_mod.F90:728
113: #5  0x421714 in __cime_comp_mod_MOD_cime_run
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/cime_comp_mod.F90:2893
113: #6  0x43aef4 in cime_driver
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/cime_driver.F90:153
113: #7  0x43af5b in main
113:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/cime_driver.F90:23
```
Rearranging the if-stmt for `meanmthflow`:
```
diff --git a/components/mosart/src/wrm/WRM_modules.F90 b/components/mosart/src/wrm/WRM_modules.F90
index ccfc8255b2..1ec24a130f 100644
--- a/components/mosart/src/wrm/WRM_modules.F90
+++ b/components/mosart/src/wrm/WRM_modules.F90
@@ -604,7 +604,9 @@ MODULE WRM_modules
      !--- return and do nothing under certain conditions
      !---------------------------------------------

-     if (damID > ctlSubwWRM%LocalNumDam .OR. damID <= 0 .or. WRMUnit%MeanMthFlow(damID,13) <= 0.01_r8) then
+     if (damID > ctlSubwWRM%LocalNumDam .OR. damID <= 0) then
+        return
+     else if (WRMUnit%MeanMthFlow(damID,13) <= 0.01_r8) then
         return
      end if

```
lets the initial run complete without errors, but the restart run encounters another error:
```
  0: At line 1064 of file /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/elm/src/biogeochem/CNPBudgetMod.F90
  0: Fortran runtime error: Index '20' of dimension 1 of array 'budg_statel' above upper bound of 19
  0:
  0: Error termination. Backtrace:
  0: #0  0x1209420 in restart_read
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/elm/src/biogeochem/CNPBudgetMod.F90:1064
  0: #1  0x121980d in __cnpbudgetmod_MOD_cnpbudget_restart
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/elm/src/biogeochem/CNPBudgetMod.F90:495
  0: #2  0x802095 in __restfilemod_MOD_restfile_read
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/elm/src/main/restFileMod.F90:695
  0: #3  0x620daf in __elm_initializemod_MOD_initialize2
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/elm/src/main/elm_initializeMod.F90:757
  0: #4  0x5e864b in __lnd_comp_mct_MOD_lnd_init_mct
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/components/elm/src/cpl/lnd_comp_mct.F90:278
  0: #5  0x441fb5 in __component_mod_MOD_component_init_cc
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/component_mod.F90:248
  0: #6  0x429992 in __cime_comp_mod_MOD_cime_init
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/cime_comp_mod.F90:1431
  0: #7  0x43ae1b in cime_driver
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/cime_driver.F90:122
  0: #8  0x43af5b in main
  0:    at /lcrc/group/e3sm/azamat/repos/E3SM-clone/driver-mct/main/cime_driver.F90:23
```

The error on Ascent is while writing initial run's restart files: lnd.log
```
 Beginning timestep   : 0001-01-07_00:00:00
    Completed timestep: 0001-01-07_00:00:00
 hist_htapes_wrapup : history tape            1 : no open file to close
 writing restart file ./ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration20220107_030557.elm.r.0001-01-07-00000.nc for model date = 0001-01-07-00000

 restFile_open: writing restart dataset at ./ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration20220107_030557.elm.r.0001-01-07-00000.nc at nstep =          288

 Opened file ./ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration20220107_030557.elm.r.0001-01-07-00000.nc to write          61
 htape_create : Opening netcdf rhtape ./ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration20220107_030557.elm.rh0.0001-01-07-00000.nc
 Opened file ./ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration20220107_030557.elm.rh0.0001-01-07-00000.nc to write          62
 htape_create : Successfully defined netcdf restart history file            1
```
and e3sm.log
```
1: 0: PIO: FATAL ERROR: Aborting... FATAL ERROR: Overflow when type cast to 4-byte integer. (/gpfs/wolf/cli115/proj-shared/testing/E3SM/
externals/scorpio/src/clib/pioc_support.c: 3373)
1: 0: Obtained 10 stack frames.
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x108cf184]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x108cf2f8]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x108cf794]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x108d56f8]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x108eb7bc]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x1089bf2c]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x105bdd6c]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x10160be8]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x100dd0b4]
1: 0: /gpfs/wolf/cli115/proj-shared/azamat/e3sm_scratch/ERS.r05_r05.IELM.ascent_gnugpu.elm-V2_ELM_MOSART_features.JNextIntegration202201
07_030557/bld/e3sm.exe() [0x100c4c34]
1: 0: --------------------------------------------------------------------------
1: 0: MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
1: 0: with errorcode -1.
1: 0:
1: 0: NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
1: 0: You may or may not see output from other processes, depending on
1: 0: exactly when Open MPI kills them.
1: 0: --------------------------------------------------------------------------
```
It'd be useful to get a debug run working on Summit or Chrysalis. This appears to be a recently added test in E3SM-Project/E3SM#4676

**Comment by hydrotian** [comment]
After your if-statement fix, does the error still come from MOSART or it's only from ELM CNPBudgetMod?

**Comment by amametjanov** [comment]
After re-arranging, the run goes further, but aborts with the error in ELM. I don't know if it's related to the first error and who would be more familiar with that part. Can you please suggest someone?

**Comment by hydrotian** [comment]
@bishtgautam An ELM error happened with doing the ELM-MOSART restart test with GNU compiler. Looks like it related to CNPBudgetMod.F90. Could you please take a look? Thanks.
