### ISSUE TITLE
PGN and TSC tests are failing

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#4789]
Looks like python errors.  

https://my.cdash.org/viewTest.php?onlyfailed&buildid=2127097

TSC:  
```
2022-02-10 11:07:25: Exception during BASELINE:
ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
multiprocessing.pool.RemoteTraceback: 
```

PGN:
```
2022-02-10 00:53:31: Exception during BASELINE:
'Data'
Traceback (most recent call last):
  File "/gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_atmnbfb/ACME/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 525, in _phase_modifying_call
    function()
  File "/gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_atmnbfb/ACME/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/pgn.py", line 205, in _compare_baseline
    for evv_elem in evv_status["Data"]["Elements"]:
KeyError: 'Data'
```

**Comment by mkstratos** [comment]
These errors are fixed in https://github.com/ESMCI/cime/pull/4166, but E3SM hasn't been updated to that version yet
