### ISSUE TITLE
Floating-point exception `ERS_D.f09_f09.IELM.pm-cpu_gnu.elm-lnd_rof_2way` 

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5293]
Repo from Nov 10th, this test fails
`ERS_D.f09_f09.IELM.pm-cpu_gnu.elm-lnd_rof_2way`

```
26: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
26: 
26: Backtrace for this error:
26: #0  0x153e2bee7d6f in ???
26: #1  0x20147a6 in __rtmmod_MOD_rtmrun
26:     at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/components/mosart/src/riverroute/RtmMod.F90:2232
26: #2  0x1fd1469 in __rof_comp_mct_MOD_rof_run_mct
26:     at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/components/mosart/src/cpl/rof_comp_mct.F90:365
26: #3  0x439db4 in __component_mod_MOD_component_run
26:     at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/driver-mct/main/component_mod.F90:728
26: #4  0x41dc4a in __cime_comp_mod_MOD_cime_run
26:     at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/driver-mct/main/cime_comp_mod.F90:2921
26: #5  0x4374ba in cime_driver
26:     at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/driver-mct/main/cime_driver.F90:153
26: #6  0x43751d in main
26:     at /global/cfs/cdirs/e3sm/ndk/repos/ndk_machinefiles_PM-add-MPICH_COLL_SYNC-MPI_Bcast/driver-mct/main/cime_driver.F90:23
```

Line of fail:
```
             if ( TRunoff%wf_ini(nr) < 0._r8 ) then
               TRunoff%wr(nr, 1) = TRunoff%wr(nr, 1) + TRunoff%wf_ini(nr)
               TRunoff%wf_ini(nr) = 0._r8
               TRunoff%yr(nr, 1) = TRunoff%wr(nr, 1) / TUnit%rlen(nr) / TUnit%rwidth(nr)  !<-- line 2232
             endif
```

**Comment by ndkeen** [comment]
If add debug prints:

```
             if ( TRunoff%wf_ini(nr) < 0._r8 ) then
               TRunoff%wr(nr, 1) = TRunoff%wr(nr, 1) + TRunoff%wf_ini(nr)
               TRunoff%wf_ini(nr) = 0._r8
               if (TUnit%rlen(nr) <= 0.0_r8) write(*,'(a,i8,es20.10)') "ndk nr, TUnit%rlen(nr)=", nr, TUnit%rlen(nr)
               if (TUnit%rwidth(nr) <= 0.0_r8) write(*,'(a,i8,es20.10)') "ndk nr, TUnit%rwidth(nr)=", nr, TUnit%rwidth(nr)
               TRunoff%yr(nr, 1) = TRunoff%wr(nr, 1) / TUnit%rlen(nr) / TUnit%rwidth(nr)
             endif
```

output:
```
26: ndk nr, TUnit%rlen(nr)=  106369    0.0000000000E+00
26: ndk nr, TUnit%rwidth(nr)=  106369   -9.9990000000E+03
```

**Comment by ndkeen** [comment]
I see I re-found this bug here: https://github.com/E3SM-Project/E3SM/issues/5540
