### ISSUE TITLE
Setup fail ModuleNotFoundError: No module named 'mpassi_cime_py' with cdash test on several machines

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5354]
The test `SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.gcp_gnu.allactive-wcprodssp`

is failing on several machines at setup with:

```
Create namelist for component mpassi
   Calling /gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_prod/E3SM/components/mpas-seaice/cime_config/buildnml
Traceback (most recent call last):
  File "/gpfs/fs1/home/e3smtest/jenkins/workspace/ACME_chrysalis_prod/E3SM/cime/CIME/utils.py", line 634, in import_and_run_sub_or_cmd
    mod = importlib.import_module(f"{compname}_cime_py")
  File "/lcrc/soft/climate/e3sm-unified/base/envs/cime_env_1.6.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mpassi_cime_py'

```

I verified that `SMS_D_Ld1.ne30pg2_EC30to60E2r2.WCYCLSSP370.pm-cpu_gnu.allactive-wcprodssp` works with current master.

@jonbob knows the issue happened in [PR #5123](https://github.com/E3SM-Project/E3SM/pull/5123)

**Comment by ndkeen** [comment]
After a re-merge of PR 5123, this test is passing for me on pm-cpu
