### ISSUE TITLE
E3SM Version 2.1 create_newcase error : module 'importlib' has no attribute 'machinery'

### ISSUE THREAD

**Issue by daofeng2007** [E3SM-Project/E3SM#5400]
When I tried to run create_newcase, I received error.
Traceback (most recent call last):
  File "/data/taoliu/taoliufile/my_e3sm/v2/E3SM/cime/scripts/./create_newcase", line 18, in <module>
    _main_func()
  File "/data/taoliu/taoliufile/my_e3sm/v2/E3SM/cime/CIME/scripts/create_newcase.py", line 385, in _main_func
    ) = parse_command_line(sys.argv, cimeroot, description)
  File "/data/taoliu/taoliufile/my_e3sm/v2/E3SM/cime/CIME/scripts/create_newcase.py", line 33, in parse_command_line
    config = Config.load(customize_path)
  File "/data/taoliu/taoliufile/my_e3sm/v2/E3SM/cime/CIME/config.py", line 224, in load
    customize_module_spec = importlib.machinery.ModuleSpec("cime_customize", None)
AttributeError: module 'importlib' has no attribute 'machinery'

**Comment by jasonb5** [comment]
@daofeng2007 Is this still an issue? If so what version of python are you using?
