### ISSUE TITLE
forrtl: error (72): floating overflow SMS_D_Ln5.ne4_oQU240.F2010.cori-knl_intel.eam-clubb_sp

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5543]
Using `SMS_D_Ln5.ne4_oQU240.F2010.cori-knl_intel.eam-clubb_sp`

```
78: forrtl: error (72): floating overflow
78: Image              PC                Routine            Line        Source
78: e3sm.exe           000000000F3174C4  Unknown               Unknown  Unknown
78: e3sm.exe           000000000EFF2810  Unknown               Unknown  Unknown
78: e3sm.exe           000000000F882246  Unknown               Unknown  Unknown
78: e3sm.exe           0000000004D05D47  advance_xm_wpxp_m         541  advance_xm_wpxp_module.F90
78: e3sm.exe           0000000004C0DFCF  advance_clubb_cor        1523  advance_clubb_core_module.F90
78: e3sm.exe           00000000037497BF  clubb_api_module_         729  clubb_api_module.F90
78: e3sm.exe           0000000002CCF764  clubb_intr_mp_clu        2253  clubb_intr.F90
78: e3sm.exe           00000000032954B2  physpkg_mp_tphysb        2542  physpkg.F90
78: e3sm.exe           000000000325F948  physpkg_mp_phys_r        1075  physpkg.F90
78: e3sm.exe           000000000EB4F1B3  Unknown               Unknown  Unknown
78: e3sm.exe           000000000EAF7D4A  Unknown               Unknown  Unknown
78: e3sm.exe           000000000EAF6DA1  Unknown               Unknown  Unknown
78: e3sm.exe           000000000EB4F59A  Unknown               Unknown  Unknown
78: e3sm.exe           000000000EFED769  Unknown               Unknown  Unknown
78: e3sm.exe           000000000F94ED5F  Unknown               Unknown  Unknown

/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/pnan/SMS_D_Ln5.ne4_oQU240.F2010.cori-knl_intel.eam-clubb_sp.rei
```

Unable to reproduce on chrysalis.
`SMS_D_Ln5.ne4_oQU240.F2010.chrysalis_intel.eam-clubb_sp`

**Comment by ndkeen** [comment]
Thought it might be possible it's related to the intermittent fails listed here https://github.com/E3SM-Project/E3SM/issues/5298

Also, noticed that this cases uses 96 MPI's with 4 threads each, which is too many. But trying 
`SMS_P48x2_D_Ln5.ne4_oQU240.F2010.cori-knl_intel.eam-clubb_sp` also fails in the same way.

**Comment by rljacob** [comment]
I'm seeing a different error message in this test now:
```
50:
50: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
50:
50: Backtrace for this error:
50: #0  0x14eda3027d4f in ???
50: #1  0x117edff in __clubb_intr_MOD_clubb_tend_cam
50:     at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_next/E3SM/components/eam/src/physics/cam/clubb_intr.F90:2083
```

**Comment by ndkeen** [comment]
I think we can close
