### ISSUE TITLE
FPE in SMS_D_Ln5.ne4_oQU240.F2010.pm-cpu_gnu.eam-clubb_sp

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#5644]
Very soon after the model starts.

```
50:
50: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
50:
50: Backtrace for this error:
50: #0  0x14eda3027d4f in ???
50: #1  0x117edff in __clubb_intr_MOD_clubb_tend_cam
50:     at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_next/E3SM/components/eam/src/physics/cam/clubb_intr.F90:2083
50: #2  0x1443c3e in tphysbc
50:     at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_next/E3SM/components/eam/src/physics/cam/physpkg.F90:2714
50: #3  0x146a172 in __physpkg_MOD_phys_run1._omp_fn.0
50:     at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_next/E3SM/components/eam/src/physics/cam/physpkg.F90:1157
```

**Comment by ndkeen** [comment]
I already have an issue for this.
https://github.com/E3SM-Project/E3SM/issues/5298

Also, just now I tried the test and it passes -- so it is still intermittent.

**Comment by rljacob** [comment]
Duplicate of #5298
