### ISSUE TITLE
floating invalid in mo_exp_sol.F90 in debug mode if not imposing a limiter on base_sol and base_sol_reset

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5646]
This is created to track and discuss solution for a known issue.

Debug test such as SMS_D_Ln5.ne4pg2_oQU480.F20TR_chemUCI-Linozv3.chrysalis_intel.eam-ne4_v3atm_rtmoff would fail with the following error message

```
  forrtl: error (65): floating invalid
71: e3sm.exe           00000000010CC46E  mo_exp_sol_mp_exp         116  mo_exp_sol.F90
71: e3sm.exe           0000000001199DB5  mo_gas_phase_chem        1156  mo_gas_phase_chemdr.F90
71: e3sm.exe           0000000000E7853D  chemistry_mp_chem        1653  chemistry.F90

```

Tentative fix to allow debug run to proceed is to impose a limiter for base_sol (and similarly for base_sol_reset) in the following block of codes
```
                if (base_sol(i,k,l) < 1.0E-30_r8) then
                      base_sol(i,k,l) = 1.0E-30_r8
                endif
                chem_prod(i,k,l) = prod(i,k,m)+ind_prd(i,k,m)
                chem_loss(i,k,l) = (base_sol(i,k,l)*exp(-delt*loss(i,k,m)/base_sol(i,k,l)) - base_sol(i,k,l))/delt
                base_sol(i,k,l) = base_sol(i,k,l)*exp(-delt*loss(i,k,m)/base_sol(i,k,l)) + delt*(prod(i,k,m)+ind_prd(i,k,m))

```
It is still unsure why a limiter is needed, and decision has not been made on the limiter value. But a solution is needed in order for debug mode to run when UCI-chem feature is enabled.

**Comment by tangq** [comment]
@wlin7 , please go ahead and add the limiter as a temporary fix for the debug test. I don't expect it will lead to large climate impact. In the meanwhile, the chemistry team will continue testing and provide a long term fix in a future PR.

**Comment by ndkeen** [comment]
Note can also reproduce this on pm-cpu with GNU if I add the invalid check (after applying changes in `wlin/atm/fix_linozv3_ncol_pcols_mismatch`)

```
472: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
472: 
472: Backtrace for this error:
472: #0  0x1498e17afd4f in ???
472: #1  0xa26d9a in __mo_exp_sol_MOD_exp_sol
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/chemistry/mozart/mo_exp_sol.F90:116
472: #2  0xa6a7db in __mo_gas_phase_chemdr_MOD_gas_phase_chemdr
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/chemistry/mozart/mo_gas_phase_chemdr.F90:1158
472: #3  0x8de229 in __chemistry_MOD_chem_timestep_tend
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/chemistry/mozart/chemistry.F90:1668
472: #4  0x1446866 in tphysac
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/physics/cam/physpkg.F90:1776
472: #5  0x1450d23 in __physpkg_MOD_phys_run2
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/physics/cam/physpkg.F90:1424
472: #6  0x6361a7 in __cam_comp_MOD_cam_run2
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/control/cam_comp.F90:307
472: #7  0x6242c8 in __atm_comp_mct_MOD_atm_run_mct
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/components/eam/src/cpl/atm_comp_mct.F90:579
472: #8  0x485684 in __component_mod_MOD_component_run
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/driver-mct/main/component_mod.F90:728
472: #9  0x46a35f in __cime_comp_mod_MOD_cime_run
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/driver-mct/main/cime_comp_mod.F90:3110
472: #10  0x482d8a in cime_driver
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/driver-mct/main/cime_driver.F90:153
472: #11  0x482ded in main
472:    at /global/cfs/cdirs/e3sm/ndk/repos/wlin_atm_fix_linozv3_ncol_pcols_mismatch/driver-mct/main/cime_driver.F90:23

/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/wlinpcols/SMS_D_Ln5.ne30pg2_EC30to60E2r2.F20TR_chemUCI-Linozv3.pm-cpu_gnu.eam-v3atm_rtmoff.winvalid
```
