### ISSUE TITLE
bad state in EOS, called from: CAAR with SMS.ne120pg2_r0125_oRRS18to6v3.F2010.pm-cpu_gnu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5868]
A test in our hi_res suite failed on pm-cpu.  This would likely be first time tests have run after the v3atm change.
This may be same issue as https://github.com/E3SM-Project/E3SM/issues/5856

`SMS.ne120pg2_r0125_oRRS18to6v3.F2010.pm-cpu_gnu`

```
4721:  bad state in EOS, called from: CAAR
4721:  bad i,j,k=           3           1           5
4721:  vertical column: dphi,dp3d,vtheta_dp
...

4721:  ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0
4721: #0  0x1c155ca in __shr_abort_mod_MOD_shr_abort_backtrace
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/share/util/shr_abort_mod.F90:104
4721: #1  0x1c1579c in __shr_abort_mod_MOD_shr_abort_abort
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/share/util/shr_abort_mod.F90:61
4721: #2  0xc97dcf in __eos_MOD_pnh_and_exner_from_eos2
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/homme/src/theta-l/share/eos.F90:140
4721: #3  0xc98817 in __eos_MOD_pnh_and_exner_from_eos
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/homme/src/theta-l/share/eos.F90:74
4721: #4  0xc9ba85 in __prim_advance_mod_MOD_compute_andor_apply_rhs
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/homme/src/theta-l/share/prim_advance_mod.F90:1152
4721: #5  0xca4611 in __prim_advance_mod_MOD_prim_advance_exp
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/homme/src/theta-l/share/prim_advance_mod.F90:213
4721: #6  0xc6eb47 in prim_step_flexible
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/homme/src/share/prim_driver_base.F90:1393
4721: #7  0xc6f8e9 in __prim_driver_base_MOD_prim_run_subcycle
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/homme/src/share/prim_driver_base.F90:1183
4721: #8  0xf16e04 in __dyn_comp_MOD_dyn_run
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/eam/src/dynamics/se/dyn_comp.F90:402
4721: #9  0xc29a4f in __stepon_MOD_stepon_run3
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/eam/src/dynamics/se/stepon.F90:522
4721: #10  0x504745 in __cam_comp_MOD_cam_run3
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/eam/src/control/cam_comp.F90:352
4721: #11  0x4fce38 in __atm_comp_mct_MOD_atm_run_mct
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/components/eam/src/cpl/atm_comp_mct.F90:583
4721: #12  0x474408 in __component_mod_MOD_component_run
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/driver-mct/main/component_mod.F90:757
4721: #13  0x45b70f in __cime_comp_mod_MOD_cime_run
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/driver-mct/main/cime_comp_mod.F90:3117
4721: #14  0x4519dd in cime_driver
4721:   at /global/u2/e/e3smtest/jenkins/workspace/ACME_Perlmutter_high_res/E3SM/driver-mct/main/cime_driver.F90:153

```

**Comment by ndkeen** [comment]
Closing as we have newer ne120 grid.
