### ISSUE TITLE
FPE in `RtmMod.F90` with `ERS_D.f09_f09.IELM.pm-cpu_gnu.elm-lnd_rof_2way`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6174]
With Jan23 master and `ERS_D.f09_f09.IELM.pm-cpu_gnu.elm-lnd_rof_2way`:
```
 22: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
 22: 
 22: Backtrace for this error:
 22: #0  0x14c010c53dbf in ???
 22: #1  0x2121b5f in __rtmmod_MOD_rtmrun
 22:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/mosart/src/riverroute/RtmMod.F90:2315
 22: #2  0x20d834b in __rof_comp_mct_MOD_rof_run_mct
 22:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/mosart/src/cpl/rof_comp_mct.F90:472
 22: #3  0x48441a in __component_mod_MOD_component_run
 22:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/component_mod.F90:734
 22: #4  0x467cd2 in __cime_comp_mod_MOD_cime_run
 22:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_comp_mod.F90:2932
 22: #5  0x481785 in cime_driver
 22:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_driver.F90:153
 22: #6  0x4817e8 in main
 22:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_driver.F90:23
```

also error with intel and DEBUG

These tests pass (with next of Mar1):
```
SMS_D.f09_f09.IELM.pm-cpu_gnu.elm-lnd_rof_2way
SMS_D.f09_f09.IELM.pm-cpu_gnu
```

**Comment by ndkeen** [comment]
With master of Jan7 2025, it still fails, but diff error mesg: 
```
 14:  Error: Negative channel storage found!   -101664.93700171793     
 14:  ERROR: mosart: negative channel storage
 14: #0  0x151c74223372 in ???
 14: #1  0x246c586 in __shr_abort_mod_MOD_shr_abort_backtrace
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/share/util/shr_abort_mod.F90:104
 14: #2  0x246c72d in __shr_abort_mod_MOD_shr_abort_abort
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/share/util/shr_abort_mod.F90:61
 14: #3  0x23537d3 in __mosart_physics_mod_MOD_euler
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/components/mosart/src/riverroute/MOSART_physics_mod.F90:688
 14: #4  0x224907e in __rtmmod_MOD_rtmrun
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/components/mosart/src/riverroute/RtmMod.F90:2603
 14: #5  0x21f9558 in __rof_comp_mct_MOD_rof_run_mct
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/components/mosart/src/cpl/rof_comp_mct.F90:472
 14: #6  0x4f3960 in __component_mod_MOD_component_run
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/driver-mct/main/component_mod.F90:734
 14: #7  0x4d7236 in __cime_comp_mod_MOD_cime_run
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/driver-mct/main/cime_comp_mod.F90:2987
 14: #8  0x4f0d15 in cime_driver
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/driver-mct/main/cime_driver.F90:153
 14: #9  0x4f0d78 in main
 14:    at /global/cfs/cdirs/e3sm/ndk/repos/c03-jan7/driver-mct/main/cime_driver.F90:23
```

**Comment by peterdschwartz** [comment]
@ndkeen I think this can be closed as the f09_f09 resolution is not supported for this test due to the negative channel storage.  See PR #6388.

**Comment by ndkeen** [comment]
got it, thanks
