### ISSUE TITLE
FPE in `pam_driver.cpp` with `SMS_D_Ln3.ne4pg2_ne4pg2.F2010-MMF2.pm-cpu_gnu`

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6187]
WIth Jan23 master and `SMS_D_Ln3.ne4pg2_ne4pg2.F2010-MMF2.pm-cpu_gnu`
As well as with DEBUG and intel.

```
 88: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
 88: 
 88: Backtrace for this error:
 88: #0  0x14c95e053dbf in ???
 88: #1  0x3a07aba in ???
 88: #2  0x3a96271 in ???
 88: #3  0x3a74f67 in ???
 88: #4  0x3a08537 in ???
 88: #5  0x3a0b43f in ???
 88: #6  0x3a78a9a in _ZN3pam10PamCoupler10run_moduleIFvRS0_EEEvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/eam/src/physics/crm/pam/external/pam_core/pam_coupler.h:147
 88: #7  0x39a4bbc in pam_driver
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/eam/src/physics/crm/pam/pam_driver.cpp:170
 88: #8  0x15cf7ff in __crm_physics_MOD_crm_physics_tend
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/eam/src/physics/crm/crm_physics.F90:1467
 88: #9  0x9121c4 in __physpkg_MOD_phys_run1
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/eam/src/physics/crm/physpkg.F90:833
 88: #10  0x654bd1 in __cam_comp_MOD_cam_run1
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/eam/src/control/cam_comp.F90:266
 88: #11  0x642009 in __atm_comp_mct_MOD_atm_run_mct
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/components/eam/src/cpl/atm_comp_mct.F90:727
 88: #12  0x489a1a in __component_mod_MOD_component_run
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/component_mod.F90:734
 88: #13  0x46e117 in __cime_comp_mod_MOD_cime_run
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_comp_mod.F90:3121
 88: #14  0x486d85 in cime_driver
 88:    at /global/cfs/cdirs/e3sm/ndk/repos/me37-jan23/driver-mct/main/cime_driver.F90:153
```

**Comment by whannah1** [comment]
@jgfouca has also noticed this and is working on a fix, although more build/run problems keep cropping up, so the fix might end up being extensive.

**Comment by ndkeen** [comment]
OK, yea I saw mention of PAM, but thought it might be related to the recent downstream merge which I think is not in Jan 23 master (?) so wanted to note there may have been issue before.

**Comment by jgfouca** [comment]
Just to clarify, I've confirmed the downstream merge is not any worse than master when it comes to this FPE, so I am not working on a fix for this specific FPE.

**Comment by ndkeen** [comment]
Same error with master of Feb 26th

**Comment by ndkeen** [comment]
Not sure what changed, but with Oct 16th master, I am not seeing this error.  Closing
