### ISSUE TITLE
eamxx: Attempt to revive old SCREAM checkout on frontier (Feb 2023) to recreate PPE cases

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6808]
One option is to simply use old restart files generated in Spring 2023 on frontier and then let newer checkout try to read them -- that currently fails (reading in old restarts), but even if it did work, the climate might be too different for this purpose.

Another option is to start with a checkout where we made some PPE (DYAMOND2) simulation (`s10-feb7`) which has a hash of `550303d290`. If I checkout that hash, it will of course not build as need machine config changes. If I simply copy over obvious changes, I get a fail that looks unrelated.

```
frontier% pwd
/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/scripts
frontier% create_test SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_craygnuamdgpu
Traceback (most recent call last):
  File "/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/scripts/create_test", line 18, in <module>
    _main_func()
  File "/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/CIME/scripts/create_test.py", line 1036, in _main_func
    Config.instance().load(customize_path)
  File "/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/CIME/config.py", line 60, in load
    obj._load_file(x, customize_module)
  File "/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/CIME/config.py", line 69, in _load_file
    raw_config = utils.import_from_file("raw_config", file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/CIME/utils.py", line 46, in import_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime_config/customize/case_post_run_io.py", line 6, in <module>
    from CIME.utils                     import new_lid, run_and_log_case_status
ImportError: cannot import name 'run_and_log_case_status' from 'CIME.utils' (/lustre/orion/cli115/proj-shared/noel/wacmy/us10-feb7/cime/CIME/utils.py)
```

**Comment by ndkeen** [comment]
@jgfouca  helping me with git foo and I made some progress.

```
git clone git@github.com:E3SM-Project/scream.git timmy
cd timmy
git submodule update --recursive --init
git checkout 550303d290
git submodule update --recursive --init

man manual edits to 
cime_config/machines/config_machines.xml
cime_config/machines/cmake_macros/amdclanggpu_frontier.cmake
```

But a 
```
create_test SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream
```

fails spio build with with:

```
gmake: *** [Makefile:139: all] Error 2
ERROR: /lustre/orion/cli115/proj-shared/noel/wacmy/timmy/externals/scorpio/src/clib/pioc_support.c:961:29: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
        piodie(fname, line, msg);
                            ^~~
/lustre/orion/cli115/proj-shared/noel/wacmy/timmy/externals/scorpio/src/clib/pioc_support.c:961:29: note: treat the string as an argument to avoid this
        piodie(fname, line, msg);
                            ^
                            "%s", 
1 warning generated.
ld.lld: error: undefined symbol: std::__throw_bad_array_new_length()
>>> referenced by argparser.cxx
>>>               CMakeFiles/spio_finfo.exe.dir/__/util/argparser.cxx.o:(std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false>::_BracketMatcher(std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false> const&))
>>> referenced by argparser.cxx
>>>               CMakeFiles/spio_finfo.exe.dir/__/util/argparser.cxx.o:(std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false>::_BracketMatcher(std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false> const&))
>>> referenced by argparser.cxx
>>>               CMakeFiles/spio_finfo.exe.dir/__/util/argparser.cxx.o:(std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false>::_BracketMatcher(std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false> const&))
>>> referenced 46 more times
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/spio_finfo/CMakeFiles/spio_finfo.exe.dir/build.make:184: tools/spio_finfo/spio_finfo.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: tools/spio_finfo/CMakeFiles/spio_finfo.exe.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....


ftn-878 ftn: WARNING PIO, File = ../../../lustre/orion/cli115/proj-shared/noel/wacmy/timmy/externals/scorpio/src/flib/pio.F90, Line = 72, Column = 7 
  A module named "PIO_TYPES" has already been directly or indirectly use associated into this scope.
```

**Comment by ndkeen** [comment]
If I update scorpio in the checkout, I can get beyond this spio error, but now I see a link error:

```
git clone git@github.com:E3SM-Project/scream.git timmy
cd timmy
git submodule update --recursive --init
git checkout 550303d290
git submodule update --recursive --init
cd externals/scorpio
git checkout master

make manual edits machine files to update versions, etc:
cime_config/machines/config_machines.xml
cime_config/machines/cmake_macros/amdclanggpu_frontier.cmake
```

```
/opt/cray/pe/cce/15.0.1/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: ../../eamxx/src/control/libscream_control.a(atmosphere_driver.cpp.o): in function `scream::control::AtmosphereDriver::add_additional_column_data_to_property_checks()':
atmosphere_driver.cpp:(.text+0xab3c): undefined reference to `std::__throw_bad_array_new_length()'
/opt/cray/pe/cce/15.0.1/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: ../../eamxx/src/control/libscream_control.a(atmosphere_driver.cpp.o): in function `scream::control::AtmosphereDriver::create_fields()::{lambda(std::set<scream::GroupRequest, std::less<scream::GroupRequest>, std::allocator<scream::GroupRequest> > const&)#1}::operator()(std::set<scream::GroupRequest, std::less<scream::GroupRequest>, std::allocator<scream::GroupRequest> > const&) const':
atmosphere_driver.cpp:(.text+0xd16b): undefined reference to `std::__throw_bad_array_new_length()'
/opt/cray/pe/cce/15.0.1/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: ../../eamxx/src/control/libscream_control.a(atmosphere_driver.cpp.o): in function `scream::control::AtmosphereDriver::set_initial_conditions()':
atmosphere_driver.cpp:(.text+0x1766d): undefined reference to `std::__throw_bad_array_new_length()'
```

**Comment by ndkeen** [comment]
OK I missed updating `cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake`.  Now it builds.

```
git clone git@github.com:E3SM-Project/scream.git timmy
cd timmy
git submodule update --recursive --init
git checkout 550303d290
git submodule update --recursive --init
cd externals/scorpio
git checkout master

make manual edits machine files to update versions, etc:
cime_config/machines/config_machines.xml
cime_config/machines/cmake_macros/crayclang-scream_frontier-scream-gpu.cmake

create_test SMS.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream 
```

**Comment by jgfouca** [comment]
Glad you got it working.

**Comment by ndkeen** [comment]
I did get this working, and it's fine if you want to close, but I was going to wait until I tested ne1024.
What we need is to generally reproduce what we did for the PPE sims over a year ago.
We know it will not be BFB, but if we can show it's not CC, I think we can go forward.
I can start another issue if needed for dealing with any issues related to results.
