### ISSUE TITLE
Seg fault -- invalid memory reference with SMS ne4pg2_ne4pg2.F2010-SCREAM-LR tests using GNU and threads

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6814]
Using Perlmutter, and only using the CPU's, I have been hitting some runtime errors. I can work-around by only using 1 thread. Note that PM only has GNU v9 and higher.  Using scream repo from Nov 16th.

Here are the 2 types of errors:
```
0:  nstep, te        8   0.25847765579133606E+10   0.25847736088010263E+10  -0.81554198863645263E-04   0.98511186977129837E+05
0:  nstep, te        9   0.25847977836494746E+10   0.25847941738245683E+10  -0.99825133346045537E-04   0.98511470124235551E+05
0:
0: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
0:
0: Backtrace for this error:
0: #0  0x7f468703f49f in ???
0: E3SM-Project/scream#1  0x16b38df in __micro_p3_interface_MOD_micro_p3_tend
0:      at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/physics/cam/micro_p3_interface.F90:1311
0: E3SM-Project/scream#2  0xc4f909 in __microp_driver_MOD_microp_driver_tend
0:      at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/physics/cam/microp_driver.F90:209
0: E3SM-Project/scream#3  0xdcea05 in tphysbc
0:      at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/physics/cam/physpkg.F90:2608
0: E3SM-Project/scream#4  0xdef7f8 in __physpkg_MOD_phys_run1._omp_fn.0
0:      at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/physics/cam/physpkg.F90:1092
0: E3SM-Project/scream#5  0x7f468783b3a5 in gomp_thread_start
0:      at ../../../cray-gcc-9.3.0-202103112153.1accb32b2394c/libgomp/team.c:123
0: E3SM-Project/scream#6  0x7f4687d964f8 in ???
0: E3SM-Project/scream#7  0x7f4687101ece in ???
0: E3SM-Project/scream#8  0xffffffffffffffff in ???
srun: error: nid003964: task 0: Segmentation fault
```

```
3: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
13: 
13: Backtrace for this error:
13: 
13: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
13: 
13: Backtrace for this error:
13: #0  0x7f8374f8949f in ???
13: #0  0x7f8374f8949f in ???
13: E3SM-Project/scream#1  0x93c797 in __modal_aero_wateruptake_MOD_modal_aero_wateruptake_dr
13: E3SM-Project/scream#1  0x93c797 in __modal_aero_wateruptake_MOD_modal_aero_wateruptake_dr
13:     at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/chemistry/utils/modal_aero_wateruptake.F90:280
13:     at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/chemistry/utils/modal_aero_wateruptake.F90:280
13: E3SM-Project/scream#2  0x881eba in __aero_model_MOD_aero_model_wetdep
13: E3SM-Project/scream#2  0x881eba in __aero_model_MOD_aero_model_wetdep
13:     at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/chemistry/bulk_aero/aero_model.F90:632
13:     at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/chemistry/bulk_aero/aero_model.F90:632
13: E3SM-Project/scream#3  0xdd2786 in tphysbc
13:     at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/physics/cam/physpkg.F90:2673
13: E3SM-Project/scream#4  0xdef7f8 in __physpkg_MOD_phys_run1._omp_fn.0
13:     at /pscratch/sd/n/ndk/wacmy/crterai_ne256_working/components/eam/src/physics/cam/physpkg.F90:1092
13: E3SM-Project/scream#5  0x7f83757853a5 in gomp_thread_start
13:     at ../../../cray-gcc-9.3.0-202103112153.1accb32b2394c/libgomp/team.c:123
```

These are the tests that have failed so far with 1 of the 2 errors above:
```
SMS_D_P16x8.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P1x16.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P1x4.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P32x4.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P8x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_P1x8.ne4pg2_ne4pg2.F2010-SCREAM-LR
```

These test do not fail and complete 5 days.
```
SMS_D_P16x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P1x1.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P1x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P1x8.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P2x1.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P2x16.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P4x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P64x1.ne4pg2_ne4pg2.F2010-SCREAM-LR
SMS_D_P64x2.ne4pg2_ne4pg2.F2010-SCREAM-LR
```

The SMS tests do fail with MEMLEAK which may or may not be issue (https://github.com/E3SM-Project/scream/issues/1318)

**Comment by rljacob** [comment]
Still an issue?

**Comment by ndkeen** [comment]
I think can still reproduce, however, 
a) this compset no longer supported
b) it's a known issue where we don't really handle running with more total threads than we have elements

**Comment by ndkeen** [comment]
Closing as no longer supporting the compset
