### ISSUE TITLE
Floating-point exception with ne4/ne30 DEBUG on chrysalis/pm-cpu with GNU

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6815]
With May27 master. I think we've seen this error before.

I see this with ne4 using `SMS_D.ne4_ne4.F2010-SCREAMv1.pm-cpu_gnu` and for ne30,
using `SMS_D_P128x2_Ln12.ne30_ne30.F2010-SCREAMv1.pm-cpu_gnu` should reproduce

Fails on this line: `ekat_pack_gen_bin_op_all(/)`

```
  0: Atmosphere step = 0
  0:   model time = 0001-01-01 00:00:00
  0:
  0:
  0: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
  0:
  0: Backtrace for this error:
  0: #0  0x15199ffb5d6f in ???
  0: E3SM-Project/scream#1  0x31244e6 in _ZN4ekatdvIdLi16EiEENS_4PackIT_XT0_EEERKT1_RKS3_
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/externals/ekat/src/ekat/ekat_pack.hpp:358
  0: E3SM-Project/scream#2  0x31244e6 in _ZZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE10dp_inverseERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiRKNS2_4ViewIPKN4ekat4PackIdLi16EEEJNS2_11LayoutRightES6_NS2_1$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/components/scream/src/physics/shoc/shoc_dp_inverse_impl.hpp:23
  0: E3SM-Project/scream#3  0x31245f8 in _ZN6Kokkos12parallel_forIiZN6scream4shoc9FunctionsIdNS_6DeviceINS_6OpenMPENS_9HostSpaceEEEE10dp_inverseERKNS_4Impl20HostThreadTeamMemberIS5_EERKiRKNS_4ViewIPKN4ekat4PackIdLi16EEEJNS_11Layout$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/externals/ekat/extern/kokkos/core/src/impl/Kokkos_HostThreadTeam.hpp:842
  0: E3SM-Project/scream#4  0x31241e5 in _ZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE10dp_inverseERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiRKNS2_4ViewIPKN4ekat4PackIdLi16EEEJNS2_11LayoutRightES6_NS2_12$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/components/scream/src/physics/shoc/shoc_dp_inverse_impl.hpp:22
  0: E3SM-Project/scream#5  0x311204a in _ZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE27update_prognostics_implicitERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiSE_SE_RKdRKNS2_4ViewIPKN4ekat4PackIdLi16EEEJN$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/components/scream/src/physics/shoc/shoc_update_prognostics_implicit_impl.hpp:100
  0: E3SM-Project/scream#6  0x30e3a56 in _ZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE18shoc_main_internalERKNS2_4Impl20HostThreadTeamMemberIS4_EERKiSE_SE_SE_SE_RKdSG_SG_RKNS2_4ViewIPKN4ekat4PackIdLi16EE$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/components/scream/src/physics/shoc/shoc_main_impl.hpp:203
  0: E3SM-Project/scream#7  0x30e09a2 in _ZZN6scream4shoc9FunctionsIdN6Kokkos6DeviceINS2_6OpenMPENS2_9HostSpaceEEEE9shoc_mainERKiS9_S9_S9_S9_S9_RKdRKN4ekat16WorkspaceManagerINSC_4PackIdLi16EEES6_EERKNS7_9SHOCInputERKNS7_15SHOCInput$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/components/scream/src/physics/shoc/shoc_main_impl.hpp:364
  0: E3SM-Project/scream#8  0x30e9bfc in _ZN6Kokkos4Impl11ParallelForIZN6scream4shoc9FunctionsIdNS_6DeviceINS_6OpenMPENS_9HostSpaceEEEE9shoc_mainERKiSB_SB_SB_SB_SB_RKdRKN4ekat16WorkspaceManagerINSE_4PackIdLi16EEES8_EERKNS9_9SHOCInp$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/externals/ekat/extern/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:867
  0: E3SM-Project/scream#9  0x30efcff in _ZNK6Kokkos4Impl11ParallelForIZN6scream4shoc9FunctionsIdNS_6DeviceINS_6OpenMPENS_9HostSpaceEEEE9shoc_mainERKiSB_SB_SB_SB_SB_RKdRKN4ekat16WorkspaceManagerINSE_4PackIdLi16EEES8_EERKNS9_9SHOCIn$
  0:    at /pscratch/sd/n/ndk/wacmy/ndk_scream_nersc-adjust-default-pelayout/externals/ekat/extern/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:940

/pscratch/sd/n/ndk/e3sm_scratch/pm-cpu/nne/SMS_D_Ln12.ne30_ne30.F2010-SCREAMv1.pm-cpu_gnu.20220527_175455_sng4r3

```

I see it may be same as https://github.com/E3SM-Project/scream/issues/1654, but that was with PACK=1.
Here I'm using default packsize.

It also fails in the same way on cori-knl with GNU.

This test works SMS_D_Ln4_P16x1.ne4_ne4.F2010-SCREAMv1.cori-knl_gnu, without threading.
But these fail: 
```
SMS_D_Ln4_P16x2.ne4_ne4.F2010-SCREAMv1.cori-knl_gnu
SMS_D_Ln4_P16x4.ne4_ne4.F2010-SCREAMv1.cori-knl_gnu
```
With Intel seems ok:
`SMS_D_P256x2_Ln12.ne30_ne30.F2010-SCREAMv1.cori-knl_intel`

**Comment by ndkeen** [comment]
This may be example of general issue when trying to use more total threads than elements.
