### ISSUE TITLE
eamxx: Occasional segfault at end of run for scream cases on pm-cpu

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#6816]
I have seen this error a few times now, so thought I should make an issue.
About 1 out of ~50/100 cases, the simulation completes, but hits fail while completing.
This means some of the scripts will not run after simulation. 
Resubmit will work

So far I might have only seen it on pm-cpu. It has happened with 768 nodes and with as few as 4 nodes.

```
  0: [EAMxx] Finalize ... done!
  0: 
  0: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
  0: 
  0: Backtrace for this error:
  0: #0  0x14d2ff69bd6f in ???
  0: E3SM-Project/scream#1  0x14d30764f3bd in __freeBlasMemPool
  0:    at ./src/crayblas_util.c:353
  0: E3SM-Project/scream#2  0x14d3054d8894 in __crayblas_shutdown
  0:    at ./src/crayblas_conf.c:232
  0: E3SM-Project/scream#3  0x14d30e6c15a2 in ???
  0: E3SM-Project/scream#4  0x14d2ff69eb08 in ???
  0: E3SM-Project/scream#5  0x14d2ff69ec99 in ???
  0: E3SM-Project/scream#6  0x14d2ff6862c3 in ???
  0: E3SM-Project/scream#7  0x4b0c29 in ???
  0:    at ../sysdeps/x86_64/start.S:120
  0: E3SM-Project/scream#8  0xffffffffffffffff in ???
```

**Comment by ndkeen** [comment]
I think we can close now as I've not been seeing this over past year.
